name: C/C++ CI docker

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          dockerfile: Dockerfile
          label: amd64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Build an image from Dockerfile
      run: docker build -t dch-webrtc:${{ matrix.label }} -f ${{ matrix.dockerfile }} .
    - name: tar zip
      run: 
        docker save -o dch-webrtc-${{ matrix.label }}.tar dch-webrtc:${{ matrix.label }}
        # echo "artifactPath=$(ls dch-webrtc-amd64.tar)" >> $GITHUB_ENV
    - name: Upload Docker Image
      uses: actions/upload-artifact@v3
      with:
        name: dch-webrtc-amd64
        path: dch-webrtc-amd64.tar 
