name: C/C++ CI docker

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          dockerfile: Dockerfile
          label: amd64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Build an image from Dockerfile
      run: 
        docker build -t docker.io/dch-webrtc:${{ matrix.label }} -f ${{ matrix.dockerfile }} .
        docker save -o dch-webrtc:${{ matrix.label }}.tar docker.io/dch-webrtc:${{ matrix.label }}
    - name: tar zip
      run: 
        tar -czf all.tar.gz dch-webrtc:${{ matrix.label }}.tar
        echo "artifactPath=$(ls all.tar.gz)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }} 
